app/models.py
from app import db
from datetime import datetime
import re


def slugify(s):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', s)


#Relationship Table
post_tags = db.Table('post_tags',
                     db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
                     db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'))
                     )


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140), unique=True)  #url
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now())

    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        self.generate_slug()

    tags = db.relationship('Tag', secondary=post_tags, backref=db.backref('posts', lazy='dynamic')) # Lazy = Return type 'posts'

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)

#Watch in console
    def __repr__(self):
        return f'<Post id: {self.id}, title: {self.title}>'


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    slug = db.Column(db.String(100), unique=True)  # url

    def __init__(self, *args, **kwargs):
        super(Tag, self).__init__(*args, **kwargs)
        self.slug = slugify(self.name)

    def __repr__(self):
        return f'<Tag id: {self.id}, title: {self.name}>'

app/posts/forms.py
from wtforms import Form, StringField, TextAreaField


class PostForm(Form):
    title = StringField('Title')
    body = TextAreaField('Body')

app/app.py
from flask import Flask
from config import Configuration
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager

app = Flask(__name__)
app.config.from_object(Configuration)

db = SQLAlchemy(app)

migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)

app/main.py
from app import app
from app import db
from posts.blueprint import posts
import view

app.register_blueprint(posts, url_prefix='/blog')

if __name__ == "__main__":
    app.run()

app/posts/blueprint.py
from flask import Blueprint
from flask import render_template

from .forms import PostForm
from models import Post, Tag

from flask import request
from app import db

from flask import redirect
from flask import url_for


posts = Blueprint("posts", __name__, template_folder='templates')


@posts.route('/create', methods=['POST', 'GET'])
def create_post():

    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']

        try:
            post = Post(title=title, body=body)
            db.session.add(post)
            db.session.commit()
        except:
            print("Something wrong!")

        return redirect(url_for('posts.index'))

    form = PostForm()
    return render_template('posts/create_post.html', form=form)



@posts.route("/")
def index():
    q = request.args.get('q')

    page = request.args.get('page')

    # Perevirka na int
    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    if q:
        posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q)) #.all()
    else:
        posts = Post.query.order_by(Post.created.desc()) #Filter From big to small

    pages = posts.paginate(page=page, per_page=5)

    return render_template('posts/index.html', posts=posts, pages=pages)


@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug == slug).first()
    tags = post.tags
    return render_template('posts/post_detail.html', post=post, tags=tags)


@posts.route('/tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug == slug).first()
    posts = tag.posts.all()
    return render_template('posts/tag_detail.html', tag=tag, posts=posts)

app/posts/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
	Create new post
{% endblock %}

{% block content_title %}
	New post
{% endblock %}

{% block content %}
	
	<div class="col-md-6">
		<form action="{{ url_for('posts.create_post')}}" method="POST">

			{% for field in form %}
				<div class="form-group">
					{{ field.label(class='form-label') }}
					{{ field(class='form-control') }}
				</div>
			{% endfor %}
			
			<button type="submit" class="btn btn-success">Create</button>

		</form>
	</div>

{% endblock %}

app/posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
	Blueprint index page
{% endblock %}

{% block content_title %}
	Posts
{% endblock %}


{% block content %}
	
	{% for post in pages.items %}

		<p>
			<a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{ post.title }}</a>
		</p>

	{% endfor %}

	<nav aria-label="...">
		<ul class="pagination">
			<li
				{% if not pages.has_prev %}
					class="page-item disabled"
				{% endif %}
			>
				<a href="./?page={{ pages.prev_num }}" aria-label="Previous"><span aria-hidden="true"class="page-link">&laquo;</span></a>
			</li>
			{% for page in pages.iter_pages() %}
				<li {% if page == pages.page %}
				class="page-item active" 
				{% endif %}>
					<a href="./?page={{ page }}"><span class="page-link">{{ page }}</span></a>
			</li>
			{% endfor %}

			<li
				{% if not pages.has_next %}
					class="page-item disabled"
				{% endif %}
			>
				<a href="./?page={{ pages.next_num }}" aria-label="Next"><span aria-hidden="true"class="page-link">&raquo;</span></a>
			</li>
		</ul>
	</nav>

{% endblock %}

app/posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
	{{ post.title }}
{% endblock %}

{% block content_title %}
	{{ post.title }}
{% endblock %}

{% block content %}
	<div class="tags">
		{% for tag in tags %}
			<a href="{{ url_for('posts.tag_detail', slug=tag.slug) }}"><span class="badge bg-primary">{{ tag.name }}</span></a>
			
		{% endfor %}
	</div>

	<div class="main-content">
	{{ post.body }}
	</div>
{% endblock %}

app/posts/templates/posts/tag_detail.html
{% extends 'base.html' %}


{% block title %}
	{{ tag.name }} posts
{% endblock %}


{% block content_title %}
	Posts for "{{ tag.name }}" tag:
{% endblock %}

{% block content %}

    {% for post in posts %}
    	<div class="post">
    		<a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{ post.title}}</a>
    	</div>
    {% endfor %}

{% endblock %} 

app/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="utf-8" />
  <title>
  	
  	{% block title %}

  	{% endblock %} | Flask app

  </title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href=" {{ url_for('index') }} ">Flask</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{ url_for('posts.index') }}">Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('posts.create_post') }}">New post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>

        <form class="d-flex" method="GET">

          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q" value="{{ request.args.get('q', '') }}">

          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>

      </div>
    </div>
</nav>

	    <div class="container">
	      <div class="row">
	        <h1>
	        	{% block content_title %}

	  			{% endblock %} 

	        </h1>
	        	{% block content %}

	  			{% endblock %}         
	      </div>
	    </div>

</body>
</html>

app/templates/index.html
{% extends 'base.html' %}


{% block title %}
  
  Blog

{% endblock %} 


{% block content_title %}

  Hello User!
{% endblock %}


{% block content %}
    Here you can create your blog
{% endblock %} 